# Site settings
title: University of Maryland
course_name: Course Name
course_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ornare aliquam mattis. Donec hendrerit sollicitudin urna. Aliquam venenatis rutrum velit, at lobortis dui cursus a. Nam varius metus in turpis maximus, ut rhoncus tellus dictum. In aliquam tortor nec mi dapibus, sit amet vehicula dolor auctor."
course_semester: "Fall 2019"
description: |
    Instructor: Rob Patro

message: Register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/CMSC858D" # the subpath of your site, e.g. /blog/
url: "https://rob-p.github.io/CMSC858D" # the base hostname & protocol for your site
# githubdir: "rob-p/CMSC858D"

# Author/user information
email: instructor-last-name@iust.ac.ir
twitter_username: username 
github_username:  username
authorurl: "http://author-url.com/page"
address: |
    Department of Computer Science
    University of Maryland
    College Park, MD

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



plugins:
    - jekyll-jalali
